### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by vidhvath28** [tiny-blocks/ksuid#17]
Consider whether any of the methods should explicitly handle exceptions. For instance, in the fromBytes method, what happens if the decoded value is shorter than expected? Should this throw an exception, or should it handle it gracefully?

**Comment by gustavofreze** [comment]
The `fromBytes` method already handles the potential issue of a decoded value being shorter than expected. The constructor of the `Payload` class validates the payload size and throws an `InvalidPayloadSize` exception if it does not match the required 16 bytes. This ensures that any issues with payload length are consistently handled through exception throwing, maintaining robustness without redundant checks.
